language: node_js
node_js:
- '0.10'
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: DKV57lP/GPwk4AOQ68SLt7FVGQp0wRvyH3qb4b70/P2gZdbOljqD1TI0N2xjCBeSjCmZri1ULfWB0oT4LFTf216jK3iB2vQqCz6u+yiFndytcAXKdEVhljonpmifcOVOqaNDqeJIUYh+c3qXVUj5AwXeSgNiqPufveERTGghwD3Iu1+aFUjhUNcvyBkmJoVPp2sXiWd0iwwpOq9kknsWzlOW7Cyet7iPIwVCOiUZ/YPBJgwKTkEqs55uk/IvARNQ93BLu/iQ5Ss9WgLDViryBejPaXymYYzuGeZFXy/8uDQF8V9eBbB+B+AYwJhoH5jvy0SzbfCFYa1tGVmrPLJli9sUtAg17WpLwWTbZ+4i+9Lgl/h454BEBgLfXp5Pf1+8vgM+33aKWoId5gvzCWCPb+chkrVwsYcTQYE6pOE1C+bDplI20ITaEgNGNSu7wOLe/f4b72FXkYUm9u7VrOb+rN3woVO2YWHgsSIL3nBEYO5kxN+QC+kVdolj94DeIfRJrypX726PJqk6MoHyA/DNtt4epjXX4f/47Ou3aXsDnrfHEPvUmx6rWD+6wv/Xsqm2g+281s+mU1sC20gVdhNaRZhDcjUi7xIunD37kbpw9sqAuTT1f0N2eWBhXxs/aZH/V4aad3nWD5isLmUgmgnKKHJfaU51Tf3McbYb+PA0DzE=
  on:
    tags: true
    repo: octoblu/nanocyte-flow-deploy-service
    all_branches: true
