language: node_js
node_js:
- '8'
services:
- redis
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: hGewUBuaOM4BiGvV8V5Tu6gSJ4aeYlnoPzAJQgPvKTBV8v9H1Of67lnz7othtUDqq2vteC39744ap9u7zLmIiZQokLYpxaj3ujPiA/tu/LZ1Ghk5NvsBsWsZ8ZIu0cskM3xceiEymemjd0Oy58Ze3DwX6rMDCNSKxRBpknAVoI+Q/guKnPPTMp5c2d/DXN1FOl7JGcwwRShhAgqI9gQNAqdsbh269owOrzLJEFc7SPfyqyF552mIndcKh2YGZ8n0kYhBblDE+7amWzY1f5tqL8+vbobf8+S5Q+q69YuZZZXverbSNA7ElLtkqnUrOZECrzUChE/lv0gKZrLYaZVSlmFQ9VyYBANkvYjld03AlbHcHzJpfZPAIK5K9UYNnPzEslTEM+6tSKZqFQWwc3hNPaQUjyWzkNMJRvAph+n3NgeGKW/rmZbdq42APMJHwIb1rGe4zukPcYu13Y8Hvnqh2DFLVf41TnnnCFUn3VOtkLUICNKWLkl3ymVqKR2OktjljjJ0kWhGjhHvLNxKvCoQuQAnMg2LBfIldswlD3NhpT13xqphNTmwp9cqyPjUZN7+VTgfCArIUD7SANmVaZeOX4/QQZpxIKeDuHLyi20TKmxHRew6lmOhrOUJ3TwHt70XvYVi7XD5NITKXKXbiiIWRL1ipY//4Oxolh4MtjsqmK0=
  on:
    branches: true
    tags: true
    repo: octoblu/nanocyte-flow-deploy-service
after_success:
- npm run coverage
- npm run mocha:json
- bash <(curl -s https://codecov.io/bash)
- bash <(curl -s https://codecov.octoblu.com/bash)
branches:
  only:
  - "/^v[0-9]/"
notifications:
  webhooks:
  - https://beekeeper.octoblu.com/webhooks/travis:ci
